version: '3'
services:
  app:
    image: golang:1.20
    restart: unless-stopped
    depends_on:
      - kafka
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
  
  kafka:
    image: confluentinc/cp-kafka:7.3.3
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - 9092:9092